### ISSUE TITLE
Contributing to `Hasty` lib

### ISSUE THREAD

**Issue by mahabubx7** [IntegerAlex/hasty-server#11]
Hi @IntegerAlex
I have seen the source code and realized that I can contribute to this. Here, I mentioned a part of the core `Hasty` code.
https://github.com/IntegerAlex/hasty-server/blob/f4f4d4a1f7d66518d054681c5fe59be6e4c0b1a0/server/index.js#L54-L80

This looks incomplete. So I would like to code here if you are okay with it. Let me know your thoughts.
👍🏼

**Comment by IntegerAlex** [comment]
Yes , Its incomplete. You can do what you think first create a Issue what you want to Include and just remember don't use third party code, or any dependencies.
you can take help from LLM but please don't include the code of LLMs.
If you need any more details feel free to ask

**Comment by mahabubx7** [comment]
> Yes , Its incomplete. You can do what you think first create a Issue what you want to Include and just remember don't use third party code, or any dependencies. you can take help from LLM but please don't include the code of LLMs. If you need any more details feel free to ask

Should I create a new issue for working on it? or this one is good to go?

**Comment by IntegerAlex** [comment]
Ya its good to go

**Comment by IntegerAlex** [comment]
If you have added 2 or more fixes create new issues with it , It helps in managing

**Comment by mahabubx7** [comment]
Thanks :)
