### ISSUE TITLE
Add sending of status code with response AND handling of different method requests on same route

### ISSUE THREAD

**Issue by priyank-mishra-1** [IntegerAlex/hasty-server#12]
Hi @IntegerAlex ,
Currently, our server does not send HTTP status codes with responses, and it does not handle different HTTP methods (GET, POST) on the same route effectively. This issue aims to address these shortcomings.
May I fix this?

**Comment by priyank-mishra-1** [comment]
For example, in this code, Post method is working but Get method is not working
![image](https://github.com/user-attachments/assets/3a16a518-f272-48d4-a7b9-bb57ebe35df9)

**Comment by IntegerAlex** [comment]
Problem with chaining is we don't have a solid foundation yet, Leave the chaining part.
But you can fix the issue of GET, and Add solid comments and make small changes Create pr
follow [Guidelines](https://github.com/IntegerAlex/hasty-server/blob/master/CONTRIBUTING.md)

**Comment by IntegerAlex** [comment]
> Hi @IntegerAlex , Currently, our server does not send HTTP status codes with responses, and it does not handle different HTTP methods (GET, POST) on the same route effectively. This issue aims to address these shortcomings. May I fix this?

just tested. Problem is which ever first gets initialized gets executed . Like if you create GET first then POST . GET will work and POST won't

**Comment by mahabubx7** [comment]
Plz check this #15 
I have already worked on it and fixed ⚒️ it.
Now, it works fine ✅ I guess.

**Comment by IntegerAlex** [comment]
Yes i am testing it out.
