### ISSUE TITLE
POST Request Query Parameters Treated as Path

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#16]
When a client makes a POST request with query parameters in the URL, Hasty Server incorrectly treats the query string as part of the path instead of parsing it as query parameters. This causes the query to be ignored and leads to incorrect request handling.

**Comment by takumade** [comment]
Assign me

**Comment by IntegerAlex** [comment]
![Screenshot 2024-10-04 023559](https://github.com/user-attachments/assets/33b8a746-d5ef-4ac5-bc29-677461a3740f)
![Screenshot 2024-10-04 023605](https://github.com/user-attachments/assets/04145752-24a5-4b2c-b7a3-4cd030c1f0b2)
![Screenshot 2024-10-04 023623](https://github.com/user-attachments/assets/71285c20-eb29-4d22-81d7-eb77e9f599ce)
