### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#2]
Create Markdown files and Docs directory,
Add basic Doc. After finalizing how to deploy we will merge docs to it.

**Comment by sooryadev007** [comment]
Hi @IntegerAlex ,

I'd like to help with this issue. Could you please assign it to me?

**Comment by IntegerAlex** [comment]
Yes sure, If you need anything let me know
I am opening discussion for docs.

**Comment by prince-63** [comment]
I Created Basic Documentation on React you can see in pull request.
