### ISSUE TITLE
Fix : Linking [contribuing guidelines ] to CONTRIBUTING.md in README

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#21]
Need fix regarding README.md

**Comment by A-4-Atom** [comment]
Hi, I'd like to fix this issue, can you assign it to me please.

**Comment by IntegerAlex** [comment]
Do Follow [Guidelines](https://github.com/IntegerAlex/hasty-server/blob/master/CONTRIBUTING.md)
