### ISSUE TITLE
Help needed : Change color 

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#30]
![Screenshot 2024-10-03 161300](https://github.com/user-attachments/assets/3dee64cf-af14-48b8-8bb4-7233858014ac)
![Screenshot 2024-10-03 161239](https://github.com/user-attachments/assets/8410cf13-6693-4b8e-8c62-b5570aaa7ff9)
 Need to change color from above to below

**Comment by IntegerAlex** [comment]
Need Contribution to change the theme to even darker. 
If anyone up do contact

**Comment by anjumnnit** [comment]
@IntegerAlex assign this to me.

**Comment by IntegerAlex** [comment]
Done

**Comment by anjumnnit** [comment]
@IntegerAlex can you please check my pull repo https://github.com/IntegerAlex/hasty-server/pull/32

**Comment by anjumnnit** [comment]
@IntegerAlex I found it little cool tho but would definitely change it if you want.

**Comment by anjumnnit** [comment]
> @IntegerAlex

Also I am not able to differentiate between the two pictures that you have attached.

**Comment by IntegerAlex** [comment]
Change as mentioned above

**Comment by IntegerAlex** [comment]
> > @IntegerAlex
> 
> Also I am not able to differentiate between the two pictures that you have attached.

Its just contrast of the images, Same but more dark to support eyes. I read a lot of Docs and black and white iritates so soft dark colors are needed.

**Comment by Nalin-khanna** [comment]
please assign this to me

**Comment by IntegerAlex** [comment]
Done
