### ISSUE TITLE
Help : Needed for Navigation ( React Dev ).

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#33]
![Screenshot 2024-10-03 171406](https://github.com/user-attachments/assets/6bad5729-0a8e-4974-8490-78b443a6871f)

Need this type of component to navigate between previous and next file for smooth flow.

**Comment by Marvie-03** [comment]
I'll take this up

**Comment by Amarjeetkumart** [comment]
#33 
Hey, i would also like to work on it can you assign it to me also?
