### ISSUE TITLE
[BUG] The Hasty Server logo is not displaying

### ISSUE THREAD

**Issue by Amarjeetkumart** [IntegerAlex/hasty-server#34]
#### The Hasty Server logo is not displaying due to an incorrect file location reference. The logo file path in the code does not point to the correct directory or file, causing it to not load on the website. This issue affects the branding and visual identity of the server. To fix this, update the file path to the correct location where the logo is stored, ensuring it's properly linked.

![Screenshot from 2024-10-04 23-53-03](https://github.com/user-attachments/assets/9d8b0fdf-d1bc-467f-80bf-e678d1ce4188)

#### Additionally, the site title is not accurately described.

**Comment by IntegerAlex** [comment]
Done you can solve it
