### ISSUE TITLE
Add github Link on Navbar (React Dev)

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#35]
![Screenshot 2024-10-05 001002](https://github.com/user-attachments/assets/256bec47-f7c2-477e-b2b3-efd0021e5158)

**Comment by Rahulagg13** [comment]
Hey, can you assign this issue to me?

**Comment by IntegerAlex** [comment]
Go for it make sure to use " view on github" for github

**Comment by Amarjeetkumart** [comment]
Hey, i would also like to work on it can you assign it to me also?

**Comment by IntegerAlex** [comment]
Already Done #42
