### ISSUE TITLE
Add : SendFile() Method in Response Object

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#44]
- Add SendFile() method in response object to send files like .pdf .img .doc .html etc.
 - Add custom header according to the file type selected 

**Need Fast**

**Comment by mahabubx7** [comment]
Can you explain in details? So I can determine and decide according to my capabilities.
My initial guess: **Adding MiME types**
For the `send()` method in `Response` class, add mime-types to send files like images, videos, pdf, etc.

**Comment by IntegerAlex** [comment]
SendFile() method will take file path and we will check mime type to add to Headers, and send the file

**Comment by IntegerAlex** [comment]
I am already working on MIME Types

**Comment by mahabubx7** [comment]
I can work on it then.
But, I might need some time to make a pull for this. (appx. 2 days maybe)
Can I contribute?

**Comment by IntegerAlex** [comment]
I have worked on half way.
Wait for my PR

**Comment by IntegerAlex** [comment]
we have to add major changes related to error handling we don't have.
