### ISSUE TITLE
TESTING : Test our Framework ( Any One with basic knowledge of Node/Express )

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#51]
- test framework and create basic API's and create issues on repo.
- Any bug as of the latest version, Report it.

**Comment by wenayy** [comment]
assign me this i will do it

**Comment by IntegerAlex** [comment]
Good, try with some basic application you have created in express just migrate it to hasty-server and test it.

**Comment by wenayy** [comment]
you can check this #56 this too

**Comment by wenayy** [comment]
> Good, try with some basic application you have created in express just migrate it to hasty-server and test it.

sure i will
