### ISSUE TITLE
Will express this issue during v 1.0.0 release : Excessive Verbose Logging on Server Start

### ISSUE THREAD

**Issue by wenayy** [IntegerAlex/hasty-server#55]
When starting the server using hasty-server, there is excessive logging of the registered routes in the console. While some logging is helpful for debugging, the current output is too verbose and can be overwhelming, especially for new users or during development.
<img width="511" alt="image" src="https://github.com/user-attachments/assets/d40e2362-8a39-4a1b-b433-066a99949b67">

a

**Comment by IntegerAlex** [comment]
That will be removed in version 1.0.0 As of now i Still consider it as BETA (<v1) And more development is needed.
