### ISSUE TITLE
Missing or Non-Functional hasty.json() Function (as express have express.json())

### ISSUE THREAD

**Issue by wenayy** [IntegerAlex/hasty-server#56]
**Description**:  
The `hasty.json()` function is not available or not functioning as expected in the `hasty-server` library. This function is typically used to parse incoming JSON requests, and its absence affects the ability to handle JSON data in API requests.

**Example Code**:
```javascript
import hasty from 'hasty-server'; // Use ES module import syntax
const app = new hasty();
app.use(hasty.json()); // This line throws an error: "hasty.json is not a function"

**Comment by IntegerAlex** [comment]
JSON parsing is already built in Inside our framework.

**Comment by wenayy** [comment]
throwing error

**Comment by wenayy** [comment]
<img width="547" alt="image" src="https://github.com/user-attachments/assets/df4031cb-cf25-4e4d-b4f5-a792ebbb4bef">

**Comment by IntegerAlex** [comment]
no like, you need to use `express.json()` to handle `json()` in incomming and outgoing http request. But hasty-server by default have Built in support for json. you don't need to use `hasty.json()`

**Comment by IntegerAlex** [comment]
> <img alt="image" width="547" src="https://private-user-images.githubusercontent.com/178035525/374753825-df4031cb-cf25-4e4d-b4f5-a792ebbb4bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzEzMTMsIm5iZiI6MTcyODQzMTAxMywicGF0aCI6Ii8xNzgwMzU1MjUvMzc0NzUzODI1LWRmNDAzMWNiLWNmMjUtNGU0ZC1iNGY1LWE3OTJlYmJiNGJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMzQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTVmZDc2NDhmYjMyZjdmYTQxOTk1NThjNTdmNzk1ODBjMWU1MGJjNWUzZWU2Mzk2OGRmMzNjYTM1ZDMxMjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oDLGl905t2LgMEpDlJ8d6ZwMJSrdEnV7mqMZApkjmZs">

Run it without that middleware

**Comment by IntegerAlex** [comment]
Is it working or do i need to add a patch to this too? @wenayy

**Comment by wenayy** [comment]
no it isn't working
