### ISSUE TITLE
HELP : Add Error Handling for HTTP Parsing

### ISSUE THREAD

**Issue by wenayy** [IntegerAlex/hasty-server#59]
Currently, if the httpParser fails to parse an incoming request, the server does not respond with an error. This can lead to silent failures, making it difficult to debug issues.
<img width="702" alt="image" src="https://github.com/user-attachments/assets/058e2c8d-ed89-4751-b0b1-c46a1e560539">

**Comment by IntegerAlex** [comment]
Frankly there is no robust mechanism for error handling till now for any method. Because i am against the use of LLM to generate code as i wanted to learn and want contributors to learn. So we are slow or just say i am slow , i am pushing patches as i am facing any issue.

**Comment by wenayy** [comment]
got it

**Comment by wenayy** [comment]
so do i need to change it or just leave
