### ISSUE TITLE
(JS-0045) Either all code paths should have explicit returns, or none of them

### ISSUE THREAD

**Issue by IntegerAlex** [IntegerAlex/hasty-server#77]
## Description
Any code paths that do not have explicit returns will return `undefined`. It is recommended to replace any implicit dead-ends that return `undefined` with a `return null` statement.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/IntegerAlex/hasty-server/issue/JS-0045/occurrences/](https://app.deepsource.com/gh/IntegerAlex/hasty-server/issue/JS-0045/occurrences/)

**Comment by Niantba** [comment]
Hello, 
I would like to work on this.

**Comment by IntegerAlex** [comment]
Go for it
